"iam": "platform settings"
# site
"iam.organization": "Organization"
"iam.menu-management": "Menu Setting"
"iam.role": "Role"
"iam.member-role-global": "Role Assignment"
"iam.root-user": "Root User Setting"

"microservicemanage": "Microservice"
"microservicemanage.microservice": "Microservice"
"microservicemanage.route-management": "Route Management"
"microservicemanage.config-management": "Config Management"
"microservicemanage.instance-management": "Instance Management"

"api": "API Manage"
"api.api-test": "API Test"

"rentsetting": "Organization settings"
# organization
"rentsetting.project": "Project"
"rentsetting.user": "User"
"rentsetting.member-role-organization": "Role Assignment"
"rentsetting.client": "Client"
"rentsetting.ldap": "LDAP"
"rentsetting.password-policy": "Password Policy"

"prosetting": "Project Manage"
# project
"prosetting.proManage": "Project Manage"
"prosetting.member-role-project": "Role Assignment"

"usercenter": "Profile"
# user
"usercenter.user-info": "User Information Maintenance"
"usercenter.password": "Password Modification"
"usercenter.organization-info": "Organization Information"
"usercenter.project-info": "Project Information"

